### ISSUE TITLE
For real though this scrollbar is janky

### ISSUE THREAD

**Issue by matthew-zhang-306** [johnfn/chips#10]
It takes at least 6 seconds just clicking around the little paper-thin scrollbar line when listening to a track to finally get it to go to the right spot in the music.

And then you learn that the spot you thought it was wasn't quite accurate so you spend another 6 seconds trying to re-adjust it.

And don't even get me started on mobile.

**Comment by matthew-zhang-306** [comment]
Semi-resolved. Make it look more intuitive and we can probably close this

**Comment by johnfn** [comment]
Should be obvious enough now, I hope.
