### ISSUE TITLE
Some profile page requests

### ISSUE THREAD

**Issue by matthew-zhang-306** [johnfn/chips#11]
- Submissions above favorites, please.
 - Can track sort be from newest to oldest instead of oldest to newest?
 - Maybe the trophies on the trophy bar could also display what track earned them? And then be sorted by quality (so all the 1st place trophies, then the 2nd place trophies, etc)
 - Can comments also be sorted from newest to oldest?

**Comment by johnfn** [comment]
Word, these are all good. Tho you know you can click on a trophy to see what entry earned it?

**Comment by matthew-zhang-306** [comment]
Yeah ik that but it would suck to just click on crud and be like "oh, okay that's from here. now on to the next one!" for like 20 trophies

**Comment by johnfn** [comment]
lol yea good point. well i also display the trophies under the entries a lil further down?

**Comment by matthew-zhang-306** [comment]
Except you can't 1) quickly gauge how many 1sts a dude has 2) know which category they are without clicking, if they won only a couple 3) tell the difference between walmart and dumpster chips

**Comment by johnfn** [comment]
do you think it would be better if i did something like "5 1sts, 2 2nds" etc and then on the actual tracks made the difference between 1 2 3 4 and 5 obvious in the trophy graphics?

**Comment by matthew-zhang-306** [comment]
No it would be better if you optimized the trophy gallery 8)

**Comment by johnfn** [comment]
Submissions above favorites, please. ✅

**Comment by johnfn** [comment]
Can track sort be from newest to oldest instead of oldest to newest? ✅

**Comment by johnfn** [comment]
Maybe the trophies on the trophy bar could also display what track earned them? ✅

**Comment by johnfn** [comment]
And then be sorted by quality (so all the 1st place trophies, then the 2nd place trophies, etc) ✅

**Comment by johnfn** [comment]
Can comments also be sorted from newest to oldest? ✅
