### ISSUE TITLE
Logout doesn't work

### ISSUE THREAD

**Issue by MisaelK** [johnfn/chips#21]
After visiting the logout page, the user keeps logged in.

More testing reveals the logout page only works when loading it in a different page or tab. Left-clicking the logout button browses to the logout page, but doesn't actually perform the logout action.

**Comment by matthew-zhang-306** [comment]
100% intentional. johnfn wants you to stay forever

Nah, you log out only if you refresh the page after pressing the button. So if you're on the log out page but then you click a link on the website, it doesn't log you out. I've brought this up to johnfn before but he hasn't done anything :/

**Comment by johnfn** [comment]
WHO doesnt do anything, @myName2243 ??? WHO????????????

**Comment by matthew-zhang-306** [comment]
...what

i said you *didn't* do anything, not that you *don't* do anything. you did something now, that's good
