### ISSUE TITLE
You've voted on Infinity% of entries - 1 of 0.

### ISSUE THREAD

**Issue by matthew-zhang-306** [johnfn/chips#5]
There's a huge problem with this statement.

1/0 is not infinity.

Also I don't think I can just not vote and be okay so you should probably make this "0" number actually more than 0.

**Comment by AkumaOkami** [comment]
lim 1/x when x->0 = ∞

**Comment by matthew-zhang-306** [comment]
That's not true. lim 1/x when x -> 0 is undefined because approaching from the negative side disagrees with approaching from the positive side.

**Comment by JordanKyser** [comment]
1/0 is mathematically and scientifically impossible. This is the case as you can't get a group of zero, contrary that you can have an empty group, but in simple division, there is no such thing as an empty group. Therefore, 1/0 is not equal to anything, so you can't get anything from this expression except for an error of a division with a denominator of 0.

@AkumaOkami As to the 1/0 = ∞, the equation is not true as 1/0 would most likely equal a non-existent number (not as in just _i_, but as in non-existent to real, irrational, and imaginary). 0/0 is the same, so the same goes for _x_/0. In a nutshell _x_/0 where _x_ is a real number, the expression's solution is non-existent.

@myName2243 We can discuss this in comparison to a linear line on a graph, and I am sure that you could also agree with me here. In a linear equation, if _y_ = _x_, then both sides of the equation have the same values, thus _m (slope)_ = 1. If _y_ = _(for example)_ 3, then the _x_ value is 3, so let's talk about the other side of this particular equation. If _x_ = _(for example)_ 5, then the _x_ value cannot be given, as this is not a function, but a relation, but trying to graph the _x_/0 equation is impossible, but the _x_ = a set number is the best example for this.

Sorry for going all out on this, but I think I made it more confusing, but I hope that this could be helpful in the future. ;)

**Comment by AkumaOkami** [comment]
@myName2243 You're absolutely right. But since we're dealing with positive values, this explains why it resolved as infinity% since my above limit is valid if the function is defined in the positive set of reals.

**Comment by johnfn** [comment]
<img width="102" alt="screen shot 2017-08-06 at 11 51 25 am" src="https://user-images.githubusercontent.com/167745/29006075-a2c65f36-7a9d-11e7-9ae4-d1f252f587e9.png">

i just do what the computer tells me to

**Comment by johnfn** [comment]
fixed
